products = [
    {
        '_id': '1',
        'name': "Dulceata de Caise",
        'image': "/images/caise.jpg",
        'description': "Un gem delicios preparat din caise proaspete și zahăr.",
        's_description': "Gem de caise autentic.",
        'category': "Jams",
        'price': 14.99,
        'rating': 4.8,
        'numReviews': 12,
        'ingredients': "Caise, zahăr",
        'countInStock': 0,
    },
    {
        '_id': "2",
        'name': "Dulceata de Trandafiri",
        'image': "/images/dulceata_de_trandafiri.jpg",
        'description': "Un gem aromat și dulce, preparat din petale de trandafiri și zahăr.",
        's_description': "Gem de trandafiri delicat.",
        'category': "Jams",
        'price': 15.99,
        'rating': 5.0,
        'numReviews': 14,
        'ingredients': "Petale de trandafiri, zahăr",
        'countInStock': 10,
    },
    {
        '_id': "3",
        'name': "Dulceata de Cireșe Negre",
        'image': "/images/apa-300x300.png",
        'description': "Un gem intens și savuros, preparat din cireșe negre și zahăr.",
        's_description': "Gem delicios de cireșe negre.",
        'category': "Jams",
        'price': 16.99,
        'rating': 4.9,
        'numReviews': 15,
        'ingredients': "Cireșe negre, zahăr",
        'countInStock': 10,
    },
    {
        '_id': "4",
        'name': "Dulceata de Prune",
        'image': "/images/otet-300x300.png",
        'description': "Gem tradițional românesc preparat din prune coapte și zahăr.",
        's_description': "Gem de prune clasic.",
        'category': "Jams",
        'price': 13.99,
        'rating': 4.7,
        'numReviews': 10,
        'ingredients': "Prune, zahăr",
        'countInStock': 10,
    },
    {
        '_id': "5",
        'name': "Dulceata de Morcov cu Prune",
        'image': "/images/logo-domnu-trandafir.png",
        'description': "Un amestec dulce și surprinzător de morcov și prune.",
        's_description': "Gem inedit de morcov și prune.",
        'category': "Jams",
        'price': 15.49,
        'rating': 4.6,
        'numReviews': 13,
        'ingredients': "Morcov, prune, zahăr",
        'countInStock': 10,
    },
    {
        '_id': "6",
        'name': "Dulceata de Nuci Verzi",
        'image': "/images/serbet-300x300.png",
        'description': "Gem preparat din nuci verzi tinere, zahăr și condimente.",
        's_description': "Gem tradițional de nuci verzi.",
        'category': "Jams",
        'price': 17.99,
        'rating': 4.8,
        'numReviews': 14,
        'ingredients': "Nuci verzi, zahăr, condimente",
        'countInStock': 10,
    },
]
