# Generated by Django 4.1.7 on 2023-08-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shippingCost',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingPrice',
            new_name='shippingCost',
        ),
    ]
